name = "sasp-intranet-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
POINTEUSE_CHANNEL_ID = "1519525957390827711"
POINTEUSE_MESSAGE_ID = "1527982879722836029"
PLAINTESASP_CHANNEL_ID = "1538289329917534328"

[triggers]
crons = ["3 10 * * SUN", "3 11 * * SUN", "0 18 * * SUN", "*/15 * * * *"]
